export const START_FETCH_MOVIE_DATA = "START_FETCH_MOVIE_DATA";
export const SUCCESS_FETCH_MOVIE_DATA = "SUCCESS_FETCH_MOVIE_DATA";
export const ERROR_FETCH_MOVIE_DATA = "ERROR_FETCH_MOVIE_DATA";

export const START_ADD_TO_FAVOURITE = "START_ADD_TO_FAVOURITE";
export const SUCCESS_ADD_TO_FAVOURITE = "SUCCESS_ADD_TO_FAVOURITE";
export const ERROR_ADD_TO_FAVOURITE = "ERROR_ADD_TO_FAVOURITE";
