export const START_GET_TEST_DATA = "START_GET_TEST_DATA";
export const SUCESS_GET_TEST_DATA = "SUCESS_GET_TEST_DATA";
export const ERROR_GET_TEST_DATA = "ERROR_GET_TEST_DATA";

export const START_GET_SINGLE_TEST_DATA = "START_GET_SINGLE_TEST_DATA ";
export const SUCESS_GET_SINGLE_TEST_DATA = "SUCESS_GET_SINGLE_TEST_DATA ";
export const ERROR_GET_SINGLE_TEST_DATA = "ERROR_GET_SINGLE_TEST_DATA ";
